import { type ShoppingItem } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import ItemModal from "~/components/ItemModal";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [items, setItems] = useState<ShoppingItem[]>([]);
  const [modalOpen, setModalOpen] = useState<boolean>(false);

  const { data: itemsData, isLoading } = api.items.getAllItems.useQuery(
    undefined,
    {
      onSuccess(items) {
        setItems(items);
      },
    }
  );

  if (!itemsData || isLoading) return <p>Loading...</p>;

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {modalOpen && (
        <ItemModal setModalOpen={setModalOpen} setItems={setItems} />
      )}
      <main className=" mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My shopping list</h2>
          <button
            onClick={() => setModalOpen(!false)}
            type="button"
            className="rounded-md bg-violet-500 p-2 text-white hover:bg-violet-700"
          >
            Add item
          </button>
        </div>
        <ul className="mt-4">
          {items.map((item) => (
            <li key={item.id}>
              <span>{item.name}</span>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
